name = "Resonances"
uuid = "7f785ca3-e171-4e0f-8881-e3bede9651ee"
authors = ["Mikhail Mikhasenko <mikhail.mikhasenko@cern.ch>"]
version = "0.1.0"

[deps]
LaTeXStrings = "b964fa9f-0449-5b57-a5c2-d3ea65f4040f"
Pluto = "c3e4b0f8-55cb-11ea-2926-15256bba5781"
PlutoUI = "7f904dfe-b85e-4ff6-b463-dae2292396a8"
WGLMakie = "276b4fcb-3e11-5398-bf8b-a0c2d153d008"
